#/bin/sh

brew tap caskroom/cask
brew tap caskroom/fonts
brew tap homebrew/core
brew tap homebrew/dupes
brew tap homebrew/fuse
brew tap homebrew/science
brew tap homebrew/services
brew tap homebrew/versions
brew tap homebrew/x11
brew tap neovim/neovim
brew tap osx-cross/avr
brew tap splhack/splhack
brew tap universal-ctags/universal-ctags

brew install apple-gcc42
brew install atk
brew install autoconf
brew install automake
brew install avr-binutils
brew install avr-gcc
brew install avr-gcc49
brew install avr-libc
brew install avr-libc49
brew install avrdude
brew install bdw-gc
brew install binutils
brew install bower
brew install cabal-install
brew install cairo
brew install clisp
brew install cloog
brew install cloog018
brew install clozure-cl
brew install cmake
brew install cmigemo
brew install --HEAD cmigemo-mk
brew install coreutils
brew install ctags-objc-ja
brew install dfu-programmer
brew install docker
brew install docker-compose
brew install docker-machine
brew install dotwrp
brew install enscript
brew install expat
brew install fftw
brew install findutils
brew install fltk
brew install fontconfig
brew install fontforge
brew install freetype
brew install fuse4x
brew install fuse4x-kext
brew install gcc
brew install gcc49
brew install gcc@4.9
brew install gd
brew install gdbm
brew install gdk-pixbuf
brew install gettext
brew install gettext-mk
brew install ghc
brew install ghostscript
brew install giflib
brew install git
brew install glib
brew install glpk
brew install gmp
brew install gmp32
brew install gmp4
brew install gmp@4
brew install gnu-sed
brew install gnuplot
brew install go
brew install gobject-introspection
brew install graphicsmagick
brew install graphviz
brew install gsettings-desktop-schemas
brew install gtk+
brew install gtk+3
brew install gtk-mac-integration
brew install gtksourceview
brew install harfbuzz
brew install haskell-platform
brew install haskell-stack
brew install hdf5
brew install hicolor-icon-theme
brew install icu4c
brew install imagemagick
brew install intltool
brew install isl
brew install isl011
brew install isl@0.11
brew install isl@0.12
brew install jbig2dec
brew install jemalloc
brew install jpeg
brew install lame
brew install libelf
brew install libepoxy
brew install libevent
brew install libffi
brew install libftdi0
brew install libiconv
brew install libmpc
brew install libmpc08
brew install libmpc@0.8
brew install libpng
brew install libsigsegv
brew install libtermkey
brew install libtiff
brew install libtool
brew install libusb
brew install libusb-compat
brew install libuv
brew install libvterm
brew install libxml2
brew install libxslt
brew install libyaml
brew install little-cms2
brew install llvm
brew install lua
brew install lua@5.1
brew install luajit
brew install --HEAD --with-properly-linked-python2-python3 macvim-kaoriya
brew install maxima
brew install mercurial
brew install metis
brew install mpfr
brew install mpfr2
brew install mpfr@2
brew install mplayer
brew install msgpack
brew install msmtp
brew install ncurses
brew install neovim --HEAD
brew install nkf
brew install node
brew install octave
brew install openssl
brew install ossp-uuid
brew install osxfuse
brew install p7zip
brew install pango
brew install pcre
brew install pdflib-lite
brew install pixman
brew install pkg-config
brew install postgresql
brew install py2cairo
brew install pyenv
brew install pyenv-virtualenv
brew install pygobject
brew install pygtk
brew install python
brew install python3
brew install qhull
brew install qrupdate
brew install r
brew install rbenv
brew install readline
brew install reattach-to-user-namespace
brew install rlwrap
brew install rtmpdump
brew install ruby
brew install ruby-build
brew install rxvt-unicode
brew install sbcl
brew install shared-mime-info
brew install smlnj
brew install sqlite
brew install sshfs
brew install suite-sparse
brew install swftools
brew install szip
brew install tbb
brew install teensy_loader_cli
brew install texinfo
brew install tig
brew install tmux
brew install unibilium
brew install --HEAD universal-ctags
brew install veclibfort
brew install vte
brew install w3m
brew install webp
brew install wget
brew install wxmac
brew install xz
brew install yasm
brew install zlib
brew install zsh
brew install zsh-completions
